import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import UpperNavbar from "@/components/shared/UpperNavbar/UpperNavbar";
import AppProvider from "@/components/provider/AppProvider";
import { Toaster } from "@/components/ui/sonner";
import { Cinzel_Decorative } from "next/font/google";
import { Raleway } from "next/font/google";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-raleway",
});

const cinzel = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-cinzel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${raleway.variable} ${cinzel.variable} antialiased`}
      >
        <AppProvider>
          <UpperNavbar />
          <Navbar />
          {children}
          <Footer />
          <Toaster  position="top-right"/>
        </AppProvider>
      </body>
    </html>
  );
}
